
@c %start of fragment

@node FreeType Fonts
@chapter FreeType Fonts
Font support for FreeType

@section Overview
The FreeType font backend is primarily used to render text on GNU/Linux
systems, but can be used on other platforms too.

@section Usage
@include defuns-cairo-ft.xml.texi

@c %end of fragment
