
@c %start of fragment

@node Patterns
@chapter Patterns
Sources for drawing

@section Overview
@code{<cairo-pattern>} is the paint with which cairo draws. The
primary use of patterns is as the source for all cairo drawing
operations, although they can also be used as masks, that is, as the
brush too.

A cairo pattern is created by using one of the many constructors, of the
form cairo_pattern_create_@emph{type}() or implicitly through
cairo_set_source_@emph{type}() functions.

@section Usage
@include defuns-cairo-pattern.xml.texi

@c %end of fragment
