
@c %start of fragment

@node Font Options
@chapter Font Options
How a font should be rendered

@section Overview
The font options specify how fonts should be rendered. Most of the time
the font options implied by a surface are just right and do not need any
changes, but for pixel-based targets tweaking font options may result in
superior output on a particular display.

@section Usage
@include defuns-cairo-font-options.xml.texi

@c %end of fragment
